# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-22 08:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('cvcode', models.IntegerField(verbose_name=b'CV Code')),
                ('expirem', models.IntegerField(verbose_name=b'Expire Month')),
                ('expirey', models.IntegerField(verbose_name=b'Expire Year')),
                ('cardnumber', models.CharField(max_length=50, verbose_name=b'Card Number')),
                ('price', models.DecimalField(decimal_places=2, max_digits=5, verbose_name=b'Price')),
            ],
            options={
                'verbose_name': 'Order',
                'verbose_name_plural': 'Orders',
            },
        ),
    ]
