# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-01 19:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_auto_20160122_1655'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='cardnumber',
        ),
        migrations.RemoveField(
            model_name='order',
            name='cvcode',
        ),
        migrations.RemoveField(
            model_name='order',
            name='expirem',
        ),
        migrations.RemoveField(
            model_name='order',
            name='expirey',
        ),
        migrations.AddField(
            model_name='order',
            name='card_type',
            field=models.CharField(default='Visa', max_length=120, verbose_name='Card Type'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='last_4',
            field=models.CharField(default='1234', max_length=50, verbose_name='Last 4 Digits'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='order',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Price'),
        ),
        migrations.AlterField(
            model_name='order',
            name='transaction_id',
            field=models.CharField(max_length=120, verbose_name='Transaction ID'),
        ),
    ]
