# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-01 23:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_auto_20160201_1958'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='last_4',
            field=models.CharField(blank=True, max_length=50, verbose_name='Last 4 Digits'),
        ),
    ]
